name = "LeafletPluto"
uuid = "4fb38181-9637-4f8d-aea6-6fc02b78bbe7"
authors = ["Florian Martin"]
version = "1.0.0"

[deps]
HypertextLiteral = "ac1192a8-f4b3-4bfe-ba22-af5b92cd3ab2"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
