name = "LeafletPluto"
uuid = "4fb38181-9637-4f8d-aea6-6fc02b78bbe7"
authors = ["Florian Martin"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
